generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CategoryExpression
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          category_expression
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:   
          display: [=name, count_citations, slug, category_name]
          sort: [name, asc]
      filter:  
          display: [name, slug, category_id]
      form:    ~
      edit:    ~
      new:     ~
