<?php

/**
 * BaseCategoryExpression
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property string $name
 * @property Doctrine_Collection $Category
 * 
 * @method integer             getCategoryId()  Returns the current record's "category_id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method Doctrine_Collection getCategory()    Returns the current record's "Category" collection
 * @method CategoryExpression  setCategoryId()  Sets the current record's "category_id" value
 * @method CategoryExpression  setName()        Sets the current record's "name" value
 * @method CategoryExpression  setCategory()    Sets the current record's "Category" collection
 * 
 * @package    citations
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoryExpression extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category_expression');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));
    }
}