<?php

/**
 * BaseNewsletter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $email
 * @property boolean $is_confirmed
 * @property clob $referer
 * @property varchar $host
 * @property varchar $keywords
 * 
 * @method varchar    getEmail()        Returns the current record's "email" value
 * @method boolean    getIsConfirmed()  Returns the current record's "is_confirmed" value
 * @method clob       getReferer()      Returns the current record's "referer" value
 * @method varchar    getHost()         Returns the current record's "host" value
 * @method varchar    getKeywords()     Returns the current record's "keywords" value
 * @method Newsletter setEmail()        Sets the current record's "email" value
 * @method Newsletter setIsConfirmed()  Sets the current record's "is_confirmed" value
 * @method Newsletter setReferer()      Sets the current record's "referer" value
 * @method Newsletter setHost()         Sets the current record's "host" value
 * @method Newsletter setKeywords()     Sets the current record's "keywords" value
 * 
 * @package    citations
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNewsletter extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('newsletter');
        $this->hasColumn('email', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('is_confirmed', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('referer', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('host', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('keywords', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}