<?php

/**
 * BaseCategoryCitation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $citation_id
 * 
 * @method integer          getCategoryId()  Returns the current record's "category_id" value
 * @method integer          getCitationId()  Returns the current record's "citation_id" value
 * @method CategoryCitation setCategoryId()  Sets the current record's "category_id" value
 * @method CategoryCitation setCitationId()  Sets the current record's "citation_id" value
 * 
 * @package    citations
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoryCitation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category_citation');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('citation_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}