<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Link', 'doctrine');

/**
 * BaseLink
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property string $website
 * @property int $statut
 * 
 * @method string getUrl()     Returns the current record's "url" value
 * @method string getWebsite() Returns the current record's "website" value
 * @method int    getStatut()  Returns the current record's "statut" value
 * @method Link   setUrl()     Sets the current record's "url" value
 * @method Link   setWebsite() Sets the current record's "website" value
 * @method Link   setStatut()  Sets the current record's "statut" value
 * 
 * @package    citations
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLink extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('link');
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('website', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('statut', 'int', null, array(
             'type' => 'int',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}