<?php

/**
 * BaseAds
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property clob $code
 * @property int $position
 * @property int $is_active
 * 
 * @method string getTitle()     Returns the current record's "title" value
 * @method clob   getCode()      Returns the current record's "code" value
 * @method int    getPosition()  Returns the current record's "position" value
 * @method int    getIsActive()  Returns the current record's "is_active" value
 * @method Ads    setTitle()     Sets the current record's "title" value
 * @method Ads    setCode()      Sets the current record's "code" value
 * @method Ads    setPosition()  Sets the current record's "position" value
 * @method Ads    setIsActive()  Sets the current record's "is_active" value
 * 
 * @package    citations
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAds extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ads');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('code', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('position', 'int', null, array(
             'type' => 'int',
             ));
        $this->hasColumn('is_active', 'int', null, array(
             'type' => 'int',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}