<?php

/**
 * BaseWord
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property int $is_active
 * @property Doctrine_Collection $Citations
 * 
 * @method string              getName()      Returns the current record's "name" value
 * @method int                 getIsActive()  Returns the current record's "is_active" value
 * @method Doctrine_Collection getCitations() Returns the current record's "Citations" collection
 * @method Word                setName()      Sets the current record's "name" value
 * @method Word                setIsActive()  Sets the current record's "is_active" value
 * @method Word                setCitations() Sets the current record's "Citations" collection
 * 
 * @package    citations
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWord extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('word');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'int', null, array(
             'type' => 'int',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Citation as Citations', array(
             'refClass' => 'WordCitation',
             'local' => 'word_id',
             'foreign' => 'citation_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggable0);
        $this->actAs($timestampable0);
    }
}