<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/01/30 17:31:27

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=citation-et-proverbe.fr',
  'username' => 'root',
  'password' => 'pAwwGXONu6FpBdhxa1Si',
  'name' => 'doctrine',
)),);
