generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Newsletter
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          newsletter
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
          display: [=email, is_confirmed]
          sort: [email, asc]
      filter: 
          display: [email, is_confirmed]
      form:    ~
      edit:    ~
      new:     ~
