<?php

/**
 * Ads
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    citations
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Ads extends BaseAds
{
		const POS_HOME_RIGHT = 'home skyscraper right';
		const POS_HOME_TOP = 'home top';
		const POS_HOME_ALTERNATE = 'home alternate';
		
		const POS_WORD_RIGHT = 'theme skyscraper right';
		const POS_WORD_TOP = 'theme top';
		const POS_WORD_ALTERNATE = 'theme alternate';
		const POS_WORDS_TOP = 'themes top';
		const POS_WORDS_RIGHT = 'themes skyscraper right';
		
		const POS_AUTH_RIGHT = 'author skyscraper right';
		const POS_AUTH_TOP = 'author top';
		const POS_AUTH_ALTERNATE = 'author alternate';
		const POS_AUTHS_TOP = 'authors top';
		const POS_AUTHS_RIGHT = 'authors skyscraper right';
		
		const POS_QUOTE_RIGHT = 'quote skyscraper right';
		const POS_QUOTE_TOP = 'quote top';
		const POS_QUOTE_ALTERNATE = 'quote alternate';
		
    public static function getAvailablePosition()
    {
    	return array(
    	  0  => self::POS_HOME_RIGHT,
    		1  => self::POS_HOME_TOP,
    		2  => self::POS_HOME_ALTERNATE,
    		3  => self::POS_WORD_RIGHT,
    		4  => self::POS_WORD_TOP,
    		5  => self::POS_WORD_ALTERNATE,
    		6  => self::POS_WORDS_TOP,
    		7  => self::POS_WORDS_RIGHT,
    		8  => self::POS_AUTH_RIGHT,
    		9  => self::POS_AUTH_TOP,
    		10 => self::POS_AUTH_ALTERNATE,
    		11 => self::POS_AUTHS_TOP,
    		12 => self::POS_AUTHS_RIGHT,
    		13 => self::POS_QUOTE_RIGHT,
    		14 => self::POS_QUOTE_TOP,
    		15 => self::POS_QUOTE_ALTERNATE
    	);
    }
    
    public function getPositionName() {
    	$position = Ads::getAvailablePosition();
    	
    	return $position[$this->getPosition()];
    }
		
    public static function getActivities()
    {
    	return array(
    	  0  => 'disabled',
    		1  => 'enabled',
    	);
    }
    
    public function getIsActiveLabel() {
    	$labels = Ads::getActivities();
    	
    	return $labels[$this->getIsActive()];
    }
    
    
}
