<?php

/**
 * AdsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ads');
    }
    
    public static function getActivesByPosition($position)
    {
    	$q = Doctrine_Core::getTable('Ads')->createQuery('a')
 								->Where('a.is_active = ?', 1)
 								->addWhere('a.position = ?', $position);
 			
			return $q->execute();
    }
}