<?php

/**
 * Author
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    citations
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Author extends BaseAuthor
{
	public function getCountCitations()
	{
    $q = Doctrine_Query::create()
    ->select('*')
    ->from('Citation c')
    ->where('c.author = ?', $this->getAuthor());
    
    $citations = $q->execute();
    
    return count($citations);
	}
	
	public function getCitations()
	{
    $q = Doctrine_Query::create()
    ->select('*')
    ->from('Citation c')
    ->where('c.author = ?', $this->getAuthor());
    
    return $q->execute();
	}
}
