<?php

/**
 * CategoryExpression
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    citations
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CategoryExpression extends BaseCategoryExpression
{
	public function getCountCitations()
	{
		return $this->Citations->count();
	}
	
	
	public function getCategoryName()
	{
	    $Category = Doctrine_Query::create()
		    ->select('*')
		    ->from('Category')
		    ->where('id = ?', $this->category_id)
		    ->execute();
	    
		return $Category[0]->getName();
	}
}
