<?php

/**
 * CategoryCitationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryCitationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryCitationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoryCitation');
    }
}