<?php

/**
 * Citation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    citations
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Citation extends BaseCitation
{
	public function getAuthorSlug()
	{
      if ($auteur = $this->getAuthorObject())
      {
        return $auteur->getSlug();
      }
      
      return false;
	}
	
	public function getAuthorObject()
	{
      if ($this->getAuthor() != '')
      {
        $auteur = Doctrine::getTable('Author')->findByAuthor($this->getAuthor());
        if (count($auteur) > 0)
        {
          return $auteur[0];
        }
      }
      
      return false;
	}
	
	public function getTwitterMessage($show_author = true)
	{

	$utm_campaign = 'citation_fr';
	if (!$show_author)
		$utm_campaign = str_replace(' ', '_', $this->author);
		
    $short_url = simplementNat::make_isdg_url('http://www.citation-et-proverbe.fr/'.$this->slug.'/?utm_source=twitter&utm_medium=twitter&utm_campaign='.$utm_campaign);
    $message = $short_url.' '.$this->quote;
    
    if ($show_author)
      $message .= ' - '.$this->author;
      
    if (strlen($message) > 140)
    {
      $message = substr($message, 0, 137).'...';
    }
    $message = str_replace($short_url.' ', '', $message);
    $message = $message.' '.$short_url;
    
    return $message;
	}
	
	public function getWords()
	{
		$quote = simplementNat::slugify($this->quote);
		
		return array_unique(split(' ', $quote));
	}
}
