<?php

/**
 * Citation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    citations
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Citation extends BaseCitation
{
	public function getAuthorSlug()
	{
      if ($auteur = $this->getAuthorObject())
      {
        return $auteur->getSlug();
      }
      
      return false;
	}
	
	public function getAuthorObject()
	{
      if ($this->getAuthor() != '')
      {
        $auteur = Doctrine::getTable('Author')->findByAuthor($this->getAuthor());
        if (count($auteur) > 0)
        {
          return $auteur[0];
        }
      }
      
      return false;
	}
	
	public function getTwitterMessage($show_author = true, $show_tag = true)
	{
		$utm_campaign = 'citation_fr';
		if (!$show_author)
			$utm_campaign = str_replace(' ', '_', $this->author);
		
    $short_url = simplementNat::make_isdg_url('http://www.citation-et-proverbe.fr/'.$this->slug.'/?utm_source=twitter&utm_medium=twitter&utm_campaign='.$utm_campaign);
    $message = $short_url.' '.$this->quote;
    
    $message_suffix = '';
    if ($show_author)
      $message_suffix .= ' - '.$this->author;
    
    if ($show_tag)
    {
      $message_suffix .= ' #citation';
      foreach($this->getActiveWords() as $word) {
      	$message_suffix .= ' #'.$word->name;
      }
    }
      
    if (strlen($message.$message_suffix) > 139)
    {
      $message = substr($message, 0, 135-strlen($message_suffix)).'...';
    }
    $message = str_replace($short_url.' ', '', $message.$message_suffix);
    $message = $message.' '.$short_url;
    
    return utf8_encode(iconv('ISO-8859-1', 'utf-8', $message));
	}
	
	public function findWords()
	{
		$quote = simplementNat::slugify($this->quote);
		
		return array_unique(split(' ', $quote));
	}
	
	public function getQuoteWord()
	{
		$quote = $this->quote;
		
		foreach ($this->getActiveWords() as $Word)
		{
			$quote = preg_replace(
				'`\b('.$Word->name.')[sx]?\b`si',
				link_to('$1', '@word?slug='.$Word->getSlug(), true),
				$quote
			);
		}

		return $quote;
	}
	
	public function getActiveWords()
	{
		$q = Doctrine_Query::create()
      ->select()
      ->from('Word w')
      ->leftJoin('w.WordCitation wc')
      ->AddWhere('wc.citation_id = ?', $this->id)
      ->andWhere('w.is_active = ?', 1);
      
    return $q->execute();
	}
}
