<?php

/**
 * Link
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    citations
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Link extends BaseLink
{

  
  public function getPage($base_url) {
    
    $file_name = 'data/downloaded/'.$this->website.'/'.str_replace('/', '__', $this->url);
    
    if (file_exists($file_name))
    { 
      $fh = fopen($file_name, 'r');
      $output = fread($fh, filesize($file_name));
      fclose($fh);
    } else {
      $ch = curl_init();
      curl_setopt($ch, CURLOPT_HEADER, 0);
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
      curl_setopt($ch, CURLOPT_URL, $base_url.$this->url); 
      $output = curl_exec($ch);
      echo '***** Request  '.$base_url.$this->url." ***** \n\n";
      curl_close($ch);
      
      $file = fopen($file_name, 'w+');
      fwrite($file, $output);
      fclose($file);
    }
    
    $this->statut = 1;
    $this->save();
        
    return $output;
  }
}
