<?php

/**
 * WordCitationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WordCitationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WordCitationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WordCitation');
    }
}