<?php

/**
 * WordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Word');
    }
  
  public function addWord($word, $citation_id) {
    
      if ($word != '')
      {
        $Words = Doctrine::getTable('Word')->findByName($word);
        if (count($Words) == 0)
        {
          echo "***** New word : $word ***** \n";
          $new_word = new Word;
          $new_word->name = $word;
          $new_word->save();
          
          $word_id = $new_word->id;
        } else {
          $word_id = $Words[0]->id;
        } 
        
        $word_citation = new WordCitation;
        $word_citation->citation_id = $citation_id;
        $word_citation->word_id = $word_id;
        $word_citation->save();
      }
  }
}