# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing


newsletter:
  url: /abonnement
  param: { module: newsletter, action: new }
  
newsletter_confirmation:
  url: /abonnement/confirmation/:code
  param: { module: newsletter, action: confirmation }
  
word:
  url:   /theme/:slug
  param: { module: word, action: show }

word_old:
  url:   /mot/:slug
  param: { module: word, action: show }
  
words:
  url:   /themes
  param: { module: word, action: index }

contact:
  url:   /contact
  param: { module: contact, action: index }
  requirements: { sf_method: [get] } 

contact_validation:
  url:   /contact/
  param: { module: contact, action: create }
  requirements: { sf_method: [post, put] } 

author:
  url:   /auteur/:slug
  param: { module: author, action: show }

authors:
  url:   /auteur
  param: { module: author, action: index }

feed:
  url:   /feed
  param: { module: citation, action: feed }
  
sitemap_page:
  url:   /sitemap/:page
  param: { module: citation, action: sitemap }
  
sitemap:
  url:   /sitemap
  param: { module: citation, action: sitemap }

random:
  url:   /random
  param: { module: citation, action: index }

single_citation:
  url:   /:slug
  param: { module: citation, action: show }
sincle_citation2:
  url:   /:slug/
  param: { module: citation, action: show }


homepage:
  url:   /
  param: { module: citation, action: last }

