# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:

all:
  Tools:
    cookie_name: citation-et-proverbe

  Contact:
    email_subject: '[citation-et-proverbe] Formulaire de contact'
    email_from: contact@citation-et-proverbe.fr
    email_to: formulaire@simplement-web.com
    email_bcc: []
    
  pager: 20
  
  newsletter:
    mail_subject_newsletter: "Confirmation de votre abonnement à la citation quotidienne"
    mail_subject_mauro: "citation -- Nouvelle inscription"
    mail_from: contact@citation-et-proverbe.fr
    mail_to: contact@citation-et-proverbe.fr
      