# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=localhost;dbname=citations
      username: admin
      password: 100282


#all:
#  doctrine:
#    class: sfDoctrineDatabase
#    param:
#      dsn:          pgsql://nat:100282@localhost/citations
