<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/01/30 17:45:01
sfConfig::add(array(
  'app_Tools_cookie_name' => 'citation-et-proverbe',
  'app_Contact_email_subject' => '[citation-et-proverbe] Formulaire de contact',
  'app_Contact_email_from' => 'contact@citation-et-proverbe.fr',
  'app_Contact_email_to' => 'formulaire@simplement-web.com',
  'app_Contact_email_bcc' => array (
),
  'app_pager' => 20,
  'app_newsletter_mail_subject_newsletter' => 'Confirmation de votre abonnement à la citation quotidienne',
  'app_newsletter_mail_subject_mauro' => 'citation -- Nouvelle inscription',
  'app_newsletter_mail_from' => 'contact@citation-et-proverbe.fr',
  'app_newsletter_mail_to' => 'contact@citation-et-proverbe.fr',
));
