generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Ads
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ads
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
          display: [=title, position_name, is_active_label, updated_at]
      filter:
          display: [title, position, is_active]
      form:    ~
      edit:    ~
      new:     ~
