Citation:
  connection: doctrine
  tableName: citation
  actAs:
    Sluggable:
      unique: true
      fields: [author]
      canUpdate: false
    Timestampable:
  columns:
    quote: {type: string()}
    author: {type: string(255)}
    source: {type: string(255)}
    website: {type: string(255)}
    is_active: {type: int}
    last_published_at: {type: datetime}
    author_last_published_at: {type: datetime}
    hash: {type: string(64)}

Link:
  connection: doctrine
  tableName: link
  actAs:
    Timestampable:
  columns:
    url: {type: string(255)}
    website: {type: string(255)}
    statut: {type: int}

Author:
  connection: doctrine
  tableName: author
  actAs:
    Sluggable:
      unique: true
      fields: [author]
      canUpdate: false
    Timestampable:
  columns:
    author: {type: string(255)}
    twitter_account: {type: string(255)}
    twitter_keys: {type: string(255)}
    is_active: {type: int}
    
Contact:
  tableName: contact
  actAs:
    Timestampable:

  columns:
    name: { type: string(255), notnull: true }
    email: { type: string(255), notnull: true }
    comments: clob
    referer: clob
    host: varchar(255)
    keywords: varchar(255)

  options:
    collate: utf8_unicode_ci
    charset: utf8
    
Word:    
  tableName: word
  actAs:
    Sluggable:
      unique: true
      fields: [name]
    Timestampable:

  columns:
    name: { type: string(255), notnull: true }
    is_active: {type: int}
    
  relations:
    Citations:
      class: Citation
      refClass: WordCitation
      foreignAlias: Words
      
  options:
    collate: utf8_unicode_ci
    charset: utf8
    
WordCitation:    
  tableName: word_citation

  columns:
    word_id: {type: integer, primary: true}
    citation_id: {type: integer, primary: true}

  options:
    collate: utf8_unicode_ci
    charset: utf8
    
Ads:
  tableName: ads
  actAs:
    Timestampable:
  columns:
    title: {type: string(255)}
    code: clob
    position: {type: int}
    is_active: {type: int}

  options:
    collate: utf8_unicode_ci
    charset: utf8
    
    

Newsletter:
  columns:
    email: varchar(255)
    is_confirmed: {type: boolean, default: false} 
    referer: clob
    host: varchar(255)
    keywords: varchar(255)
    
  actAs:
    Timestampable:
  
  options:
    collate: utf8_unicode_ci
    charset: utf8

    
Category:    
  tableName: category
  actAs:
    Sluggable:
      unique: true
      fields: [name]
    Timestampable:

  columns:
    name: { type: string(255), notnull: true }
    is_active: {type: int}
    
  relations:
    Expressions:
      class: CategoryExpression
      local: id
      foreign: category_id
      
  options:
    collate: utf8_unicode_ci
    charset: utf8

    
CategoryExpression:    
  tableName: category_expression
  actAs:
    Sluggable:
      unique: true
      fields: [name]

  columns:
    category_id: {type: integer}
    name: { type: string(255), notnull: true }
  relations:
    Citations:
      class: Citation
      refClass: CategoryCitation
      foreignAlias: CategoriesExpression

  options:
    collate: utf8_unicode_ci
    charset: utf8

    
CategoryCitation:    
  tableName: category_citation

  columns:
    category_expression_id: {type: integer, primary: true}
    citation_id: {type: integer, primary: true}

  options:
    collate: utf8_unicode_ci
    charset: utf8
    
    